
// for fetch weather
export const START_FETCH_WEATHER = 'START_FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
export const FETCH_SUGGESTED_SUCCESS = 'FETCH_SUGGESTED_SUCCESS';
export const FETCH_SUGGESTED_FAILED = 'FETCH_SUGGESTED_FAILED';


// for auth