
// for fetch weather
export const START_FETCH_WEATHER = 'START_FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
export const GET_COUNTRY = 'GET_COUNTRY';
export const FETCH_SUGGESTED_SUCCESS = 'FETCH_SUGGESTED_SUCCESS';
export const FETCH_SUGGESTED_FAILED = 'FETCH_SUGGESTED_FAILED';
export const CHANGE_CITY_SUCCESS = 'CHANGE_CITY_SUCCESS';
export const CHANGE_CITY_FAILED = 'CHANGE_CITY_FAILED';
export const FETCH_WETHER_BY_TODAY_SUCCESS = 'FETCH_WETHER_BY_TODAY_SUCCESS';
export const FETCH_WEATHER_FAILED_BY_TODAY = 'FETCH_WEATHER_BY_TODAY_FAILED';
// for auth


export const START_PROCESS = 'START_PROCESS';
export const END_PROCESS = 'END_PROCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const GET_ERRORS = 'GET_ERRORS';