
// for fetch weather
export const START_FETCH_WEATHER = 'START_FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
export const GET_COUNTRY = 'GET_COUNTRY';
export const FETCH_SUGGESTED_SUCCESS = 'FETCH_SUGGESTED_SUCCESS';
export const FETCH_SUGGESTED_FAILED = 'FETCH_SUGGESTED_FAILED';
export const CHANGE_CITY_SUCCESS = 'CHANGE_CITY_SUCCESS';
export const CHANGE_CITY_FAILED = 'CHANGE_CITY_FAILED';
export const FETCH_WETHER_BY_TODAY_SUCCESS = 'FETCH_WETHER_BY_TODAY_SUCCESS';
export const FETCH_WEATHER_FAILED_BY_TODAY = 'FETCH_WEATHER_BY_TODAY_FAILED';
// for auth