var list_Suggest = [
  { id: 1, value: "Chicago" },
  { id: 2, value: "Miami" },
  { id: 3, value: "Houston" },
  { id: 4, value: "Paris" },
  { id: 5, value: "Barcelona" },
  { id: 6, value: "Hawaii" },
  { id: 7, value: "Kabul" },
  { id: 8, value: "Tirana" },
  { id: 9, value: "Tirana" },
  { id: 10, value: "Luanda" },
  { id: 11, value: "Yerevan" },
  { id: 12, value: "Canberra" },
  { id: 13, value: "Chicago" },
  { id: 14, value: "Vienna" },
  { id: 15, value: "Baku" },
  { id: 16, value: "Nassau" },
  { id: 17, value: "Manama" },
  { id: 17, value: "Dhaka" },
  { id: 18, value: "Bridgetown" },
  { id: 19, value: "Minsk" },
  { id: 20, value: "Brussels" },
  { id: 21, value: "Belmopan" },
  { id: 22, value: "Thimphu" },
  { id: 23, value: "Sarajevo" },
  { id: 24, value: "Gaborone" },
  { id: 25, value: "Brasilia" },
  { id: 26, value: "Sofia" },
  { id: 27, value: "Praia" },
  { id: 28, value: "Santiago" },
  { id: 29, value: "Beijing" },
  { id: 30, value: "Bogota" },
  { id: 31, value: "Moroni" },
  { id: 32, value: "Brazzaville" },
  { id: 33, value: "Kinshasa" },
  { id: 34, value: "Abidjan" },
  { id: 35, value: "Zagreb" },
  { id: 36, value: "Havana" },
  { id: 37, value: "Nicosia" },
  { id: 38, value: "Prague" },
  { id: 39, value: "Copenhagen" },
  { id: 40, value: "Djibouti" },
  { id: 41, value: "Roseau" },
  { id: 42, value: "Dili" },
  { id: 43, value: "Quito" },
  { id: 44, value: "Cairo" },
  { id: 45, value: "Malabo" },
  { id: 46, value: "Tallinn" },
  { id: 47, value: "Asmara" },
  { id: 48, value: "Suva" },
  { id: 49, value: "Helsinki" },
  { id: 50, value: "Libreville" },
  { id: 51, value: "Banjul" },
  { id: 52, value: "Tbilisi" },
  { id: 53, value: "Berlin" },
  { id: 54, value: "Saint George's" },
  { id: 55, value: "Guatemala City" },
  { id: 56, value: "Conakry" },
  { id: 57, value: "Bissau" },
  { id: 58, value: "Georgetown" },
  { id: 59, value: "Reykjavik" },
  { id: 60, value: "Delhi" },
  { id: 61, value: "Jakarta" },
  { id: 62, value: "Tehran" },
  { id: 63, value: "Baghdad" },
  { id: 64, value: "Dublin" },
  { id: 65, value: "Rome" },
  { id: 66, value: "Kingston" },
  { id: 67, value: "Tokyo" },
  { id: 68, value: "Amman" },
  { id: 69, value: "Astana" },
  { id: 70, value: "Nairobi" },
  { id: 71, value: "Tarawa" },
  { id: 72, value: "Pyongyang" },
  { id: 73, value: "Seoul" },
  { id: 74, value: "Kuwait City" },
  { id: 75, value: "Bishkek" },
  { id: 76, value: "Vientiane" },
  { id: 77, value: "Riga" },
  { id: 78, value: "Beirut" },
  { id: 79, value: "Maseru" },
  { id: 80, value: "Monrovia" },
  { id: 81, value: "Tripoli" },
  { id: 82, value: "Vaduz" },
  { id: 83, value: "Luxembourg" },
  { id: 84, value: "Skopje" },
  { id: 85, value: "Antananarivo" },
  { id: 86, value: "Lilongwe" },
  { id: 87, value: "Kuala Lumpur" },
  { id: 88, value: "Male" },
  { id: 89, value: "Bamako" },
  { id: 90, value: "Valletta" },
  { id: 91, value: "Majuro" },
  { id: 92, value: "Nouakchott" },
  { id: 93, value: "Port Louis" },
  { id: 94, value: "Mexico City" },
  { id: 95, value: "Palikir" },
  { id: 96, value: "Chisinau" },
  { id: 97, value: "Monaco" },
  { id: 98, value: "Ulaanbaatar" },
  { id: 99, value: "Podgorica" },
  { id: 100, value: "Rabat" },
  { id: 101, value: "Maputo" },
  { id: 102, value: "Naypyidaw" },
  { id: 103, value: "Windhoek" },
  { id: 104, value: "Kathmandu" },
  { id: 105, value: "Amsterdam" },
  { id: 106, value: "Wellington" },
  { id: 107, value: "Managua" },
  { id: 108, value: "Niamey" },
  { id: 109, value: "Abuja" },
  { id: 110, value: "Oslo" },
  { id: 111, value: "Muscat" },
  { id: 112, value: "Islamabad" },
  { id: 113, value: "Koror" },
  { id: 114, value: "Panama City" },
  { id: 115, value: "Port Moresby" },
  { id: 116, value: "Asunción" },
  { id: 117, value: "Lima" },
  { id: 118, value: "Manila" },
  { id: 119, value: "Warsaw" },
  { id: 120, value: "Lisbon" },
  { id: 121, value: "Doha" },
  { id: 122, value: "Bucharest" },
  { id: 123, value: "Moscow" },
  { id: 124, value: "Kigali" },
  { id: 125, value: "Basseterre" },
  { id: 126, value: "Castries" },
  { id: 127, value: "Kingstown" },
  { id: 128, value: "Apia" },
  { id: 129, value: "San Marino" },
  { id: 130, value: "Sao Tome" },
  { id: 131, value: "Riyadh" },
  { id: 132, value: "Dakar" },
  { id: 133, value: "Belgrade" },
  { id: 134, value: "Victoria" },
  { id: 135, value: "Freetown" },
  { id: 136, value: "Singapore" },
  { id: 137, value: "Bratislava" },
  { id: 138, value: "Ljubljana" },
  { id: 139, value: "Honiara" },
  { id: 140, value: "Mogadishu" },
  { id: 141, value: "Madrid" },
  { id: 142, value: "Colombo" },
  { id: 143, value: "Khartoum" },
  { id: 144, value: "Paramaribo" },
  { id: 145, value: "Mbabana" },
  { id: 146, value: "Stockholm" },
  { id: 147, value: "Bern" },
  { id: 148, value: "Apia" },
  { id: 149, value: "Damascus" },
  { id: 150, value: "Taipei" },
  { id: 151, value: "Dushanbe" },
  { id: 152, value: "Dar es Salaam" },
  { id: 153, value: "Bangkok" },
  { id: 154, value: "Lome" },
  { id: 155, value: "Nuku'alofa" },
  { id: 156, value: "Port of Spain" },
  { id: 157, value: "Tunis" },
  { id: 158, value: "Ankara" },
  { id: 159, value: "Ashgabat" },
  { id: 160, value: "Funafuti" },
  { id: 161, value: "Kampala" },
  { id: 162, value: "Kiev" },
  { id: 163, value: "Abu Dhabi" },
  { id: 164, value: "London" },
  { id: 165, value: "Washington D.C." },
  { id: 166, value: "Montevideo" },
  { id: 168, value: "Tashkent" },
  { id: 169, value: "Port Vila" },
  { id: 170, value: "Vatican City" },
  { id: 171, value: "Caracas" },
  { id: 172, value: "Hanoi" },
  { id: 173, value: "Sanaa" },
  { id: 174, value: "Lusaka." },
  { id: 175, value: "Harare" },
];
function randomInteger(start, end) {
  return Math.floor(Math.random() * (end - start + 1)) + start;
}
var item_Suggest = [];
for (var i = 0; i < 6; i++) {
  const temp = randomInteger(parseInt(1), parseInt(list_Suggest.length));
  for (var j = 0; j < list_Suggest.length; j++)
    if (temp === list_Suggest[j].id)
      item_Suggest.push({ id: temp, value: list_Suggest[j].value });
}
export default item_Suggest;